name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Upload Playwright report to S3
        run: |
          REPORT_DIR="run-${{ github.run_id }}-${{ github.run_attempt }}"
          aws s3 cp ./playwright-report s3://$S3_BUCKET/$REPORT_DIR/ --recursive
          echo "::notice title=HTML report url::http://${S3_BUCKET}.s3-website.${AWS_REGION}.amazonaws.com/${REPORT_DIR}/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
          S3_BUCKET: playwright-reports-aviv
